export const sampleTexts: Record<string, string> = {
  sample1: `The science of learning is a relatively new discipline that uses cognitive research to understand how people learn. Evidence shows that many commonly accepted learning strategies are ineffective. For example, re-reading text and highlighting important passages, while popular among students, have been shown to be among the least effective studying methods. On the other hand, techniques like spaced repetition and retrieval practice have demonstrated remarkable effectiveness in improving long-term retention. Spaced repetition involves reviewing material at increasingly longer intervals, while retrieval practice involves actively recalling information rather than simply re-reading it.

Understanding how memory works is crucial. Human memory isn't designed to store information like a computer; instead, it reconstructs information each time we recall it. This is why active recall strengthens memory - each time we retrieve information, we reinforce neural pathways. Additionally, the brain processes information more effectively when it can connect new knowledge to existing frameworks, a concept known as schema building. By actively connecting new information to what we already know, we create stronger, more accessible memories.`,

  sample2: `Psychology is the scientific study of mind and behavior. Psychologists seek to understand the mental processes and behaviors of individuals and groups through research, experimentation, and observation. The field encompasses various subfields including cognitive psychology, social psychology, clinical psychology, and developmental psychology. Research methods in psychology range from controlled laboratory experiments to naturalistic observation, and from qualitative interviews to statistical analyses of large datasets. 

The discipline has made significant contributions to our understanding of perception, cognition, emotion, personality, social behavior, and the treatment of mental health conditions. Modern psychological research often integrates insights from related fields such as neuroscience, anthropology, sociology, and computer science. This interdisciplinary approach has led to breakthroughs in areas such as cognitive neuroscience, behavioral economics, and artificial intelligence.`,

  sample3: `The history of computing traces back to ancient calculating devices like the abacus. However, modern computing began with Charles Babbage's Analytical Engine design in the 1830s, considered the first general-purpose computer concept. The early 20th century saw theoretical foundations established by Alan Turing and others. ENIAC, completed in 1945, was the first general-purpose electronic computer. The invention of the transistor in 1947 revolutionized computing, leading to smaller, more reliable machines. 

Personal computing emerged in the 1970s with the Altair 8800 and Apple II. The 1990s brought the World Wide Web, transforming computers from calculation tools into communication devices. Today's computing landscape includes cloud computing, artificial intelligence, and ubiquitous mobile devices. The rapid evolution continues with quantum computing, edge computing, and increasingly sophisticated machine learning algorithms shaping the future of technology and society.`,
  sample4: `Miłość… jedno słowo, a kryje w sobie ocean emocji. Od delikatnego muśnięcia pierwszego zauroczenia, przez burzliwe fale namiętności, aż po spokojną przystań trwałego uczucia. To siła, która potrafi uskrzydlić, dodać sensu szarej codzienności i rozświetlić najciemniejsze zakątki duszy.

Miłość to nie tylko romantyczne uniesienia pod rozgwieżdżonym niebem. To także codzienne gesty troski, wspólnie wypita poranna kawa, cierpliwe wysłuchanie trosk drugiej osoby. To umiejętność kompromisu, akceptacji wad i celebrowania zalet. To radość z sukcesów ukochanej osoby i wsparcie w trudnych chwilach.

Prawdziwa miłość dojrzewa z czasem, stając się głębsza i bardziej świadoma. Przetrwa próby, umocni więzi i pozwoli dwojgu ludziom iść razem przez życie, trzymając się za ręce. To bezwarunkowe oddanie, poczucie bezpieczeństwa i pewność, że gdzieś na świecie jest ktoś, kto rozumie nas bez słów i kocha bezwarunkowo. Miłość jest najpiękniejszym darem, jaki możemy ofiarować i otrzymać.`
};
